"""Initial migration.

Revision ID: 87e23c4927e1
Revises: eeb369fb9399
Create Date: 2024-10-04 17:46:08.462254

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '87e23c4927e1'
down_revision = 'eeb369fb9399'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('county', sa.String(length=50), nullable=False))
    op.add_column('users', sa.Column('sub_county', sa.String(length=50), nullable=False))
    op.add_column('users', sa.Column('town', sa.String(length=50), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'town')
    op.drop_column('users', 'sub_county')
    op.drop_column('users', 'county')
    # ### end Alembic commands ###
